spring.application.name=api1

# Conexión a la Base de Datos mediante variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Puerto del servidor
server.port=${PORT:8080}

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Formato de respuesta de error limpia
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-exception=false
